# Generated by Django 2.1.1 on 2018-09-24 05:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_sharefile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sharefile',
            unique_together={('sender', 'receiver', 'file_id')},
        ),
    ]
